### ISSUE TITLE
'num-processes=1' 

### ISSUE THREAD

**Issue by yinjiangjin** [sumitsk/marl_transfer#1]
Hi, authors, thank you open source your code very much. 
Question:
      I set the argument 'num-processes=1' and run this code, an error occurred as follows:
'''
File "g:\workplace\ai\marl_transfer\src\gym-vecenv\gym_vecenv\dummy_vec_env.py", line 40, in reset
    self.buf_obs[t][i] = x
IndexError: list index out of range
'''
But when setting 'num-processes>1', it's no problem.

**Comment by agakshat** [comment]
Hi

That’s a known bug, which we haven’t yet gotten to due to time crunch. We always ran with multiple processes in parallel so this bug didn’t practically pose any problem. If you can fix it and create a pull, that would definitely be very useful!

**Comment by yinjiangjin** [comment]
Ok, I got it! Thank you!
