### ISSUE TITLE
code implementation with recurrent policy

### ISSUE THREAD

**Issue by wanghuimu** [sumitsk/marl_transfer#2]
Hi:
  Your work is excellent! I found that your code implementation dose not consider the recurrent policy (Like GRU or LSTM). I tried to add the recurrent policy based on your code and ikostrikov/pytorch-a2c-ppo-acktr-gail, but it seems didn’t work. Do you have the plan to add recurrent policy?

**Comment by agakshat** [comment]
Hi

Thanks for your interest, but we do not have any plans to experiment with recurrent policies. While nothing in the proposed communication architecture precludes using recurrent policy architectures, reinforcement learning is an experimental science where the implementation choices do end up mattering quite a bit, so it's difficult to say why your implementation might not be working.
